username = input("username : ")
password = input("password : ")

if username == "abcd" and password == "1234":
    print("Done !!")
    print("-----Welcome to BorntoDev Shop-----")
    print("       ")
    print("What do you want to buy ?")
    print("1. iphone 15 (25,000 THB)")
    print("2. iphone 15 Pro (35,000 THB)")
    print("3. iphone 15 Pro MAx (45,000 THB)")
    select = input(">> ")
    if select == "1":
        print("1. iphone 15 (25,000 THB)")
        print("How many iphone 15 do you want ?")
        a = input(">> ")
        iphonea = int(25000)
        totala = iphonea*int(a)
        print("Total =", totala, "THB")
    elif select == "2":
        print("2. iphone 15 Pro (35,000 THB)")
        print("How many iphone 15 Pro do you want ?")
        a = input(">> ")
        iphoneb = int(35000)
        totalb = iphoneb*int(a)
        print("Total =", totalb, "THB")
    elif select == "3":
        print("3. iphone 15 Pro MAx (45,000 THB)")
        print("How many iphone 15 Pro Max do you want ?")
        a = input(">> ")
        iphonec = int(45000)
        totalc = iphonec*int(a)
        print("Total =", totalc, "THB")
    else: print("You got only 3 choices for select !!")
else: print("username or password was incorrect !!")